name: LeetCode Streak Guardian

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Streak Guardian
        run: node src/index.js
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          LEETCODE_EMAIL: ${{ secrets.LEETCODE_EMAIL }}
          LEETCODE_PASSWORD: ${{ secrets.LEETCODE_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          FORCE_LOGIN_TEST: ${{ secrets.FORCE_LOGIN_TEST }}